name: Ros build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_docker:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    container: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: build
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: larr_planner larr_planner_ros2
          target-ros2-distro: humble

  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          extensions: 'cc,h'
          style: file
          clangFormatVersion: '10'
          check-path: '.'
